--STEP 1 : CREATE A DATABASE:

CREATE DATABASE BANKINGDB;

--STEP 2 : CONNECT TO ABOVE DATABASE:

USE BANKINGDB;

--STEP 3 : CREATE SCHEMA TO ORGANIZE THE TABLES

CREATE SCHEMA BANK;               --SCHEMA 1

CREATE SCHEMA ACCOUNT;			  --SCHEMA 2

CREATE SCHEMA TRANSACTIONS;         --SCHEMA 3


--STEP 4 : CREATE TABLE BANK:

CREATE TABLE BANK.TBLBANK
(
	BankId   BIGINT NOT NULL CONSTRAINT PK_BankId  PRIMARY KEY IDENTITY(1000,1),
	BankDetails VARCHAR(50) NULL
);


-- STEP 5 : INSERT DATA INTO TABLE BANK:

INSERT INTO BANK.TBLBANK
VALUES
('State Bank Of India'),
('State Bank of Mysore'),
('State Bank of Hyderbad'),
('ICICI'),
('Punjab Natitional Bank'),
('HDFC'),
('IDBI'),
('Karnataka Bank'),
('Syndicate Bank'),
('Canara Bank'),
('Citi Bank'),
('Wells Fargo'),
('Discover'),
('TCF');

--STEP 6 : CREATE TABLE ADDRESS:

CREATE TABLE BANK.TBLADDRESS
(
	AddId  BIGINT NOT NULL CONSTRAINT PK_Address PRIMARY KEY IDENTITY(1000,1),
	AddLine1  VARCHAR(100) NULL,
	AddLine2  VARCHAR(50) NULL,
	AddCity VARCHAR(50) NULL,
	AddPostalCode  VARCHAR(50) NULL,
	AddState  VARCHAR(50) NULL,
	AddCountry  VARCHAR(50) NULL
)


--STEP 7 : INSERT DATA INTO TABLE ADDRESS:

INSERT INTO BANK.TBLADDRESS
VALUES
('9730 37th Place North','Apt#204','Plymouth','55441','MN','USA'),

('Kombettu House','Padavu,Ujirpade Post Balnad','Puttur','574203','Karnataka','India'),

('302,Sai Manor Towers','X Roads,SR Nagar','Hyderabad','574038','Andra Pradesh','India');

--STEP 8 : CREATE TABLE BRANCHYPE:

CREATE TABLE BANK.TBLBRANCHTYPE       ----Branchtype short form (Bt)
(
	 BtId BIGINT NOT NULL CONSTRAINT PK_BranchType PRIMARY KEY IDENTITY(1000,1),
	 BtTypeCode  CHAR(2),
	 BtTypeDesc  VARCHAR(100)
);

--STEP 9 : INSERT DATA INTO TABLE BRANCH:

INSERT INTO BANK.TBLBRANCHTYPE
VALUES
('LU','Large Urban'),
('SR','Small Rural'),
('HO','Head Office');

--STEP 10 : CREATE TABLE BRANCH :
 
CREATE TABLE BANK.TBLBRANCH                 --BRANCH SHORT FORM IS (BR)
(
	BrId	BIGINT NOT NULL CONSTRAINT PK_Branch PRIMARY KEY  IDENTITY (1000,1),

	BrBankId_Fk BIGINT NULL CONSTRAINT FK_Of_TblBranch_from_tblBank 
	REFERENCES BANK.TBLBANK(BankId),

	BrAddress_Fk BIGINT NULL CONSTRAINT FK_Of_TblBranch_from_tblAddress 
	REFERENCES BANK.TBLADDRESS(AddId),

	BrBranchTypeCode_Fk BIGINT NULL CONSTRAINT FK_Of_TblBranch_from_tblBranchType
	REFERENCES BANK.TBLBRANCHTYPE(BtId),

	BrBranchName VARCHAR(100) NULL,

	BrBranchPhone1 NUMERIC(10,0) NULL CONSTRAINT Ck_BranchPhone1 CHECK(LEN(BrBranchPhone1)=10)
	CONSTRAINT Uq_BranchPhone1 UNIQUE,

	BrBranchPhone2 NUMERIC(10,0) NULL CONSTRAINT Ck_BranchPhone2 CHECK(LEN(BrBranchPhone2)=10)
	CONSTRAINT Uq_BranchPhone2 UNIQUE,

	BrBranchFax NUMERIC(10,0) NULL CONSTRAINT Ck_BranchFax CHECK(LEN(BrBranchFax)=10)
	CONSTRAINT Uq_BrBranchFax UNIQUE,

	BrBranchEmail VARCHAR(50) NULL CONSTRAINT Uq_BrBranchEmail UNIQUE,

	BrBranchIFSC  VARCHAR(20) NULL 
);

--STEP 11 :INSERT DATA INTO BRANCH:

INSERT INTO BANK.TBLBRANCH
VALUES
(1011,1000,1001,'Golden Valley',3234164705,3234164095,7639541522,
'wellsfargogv@wellsfargo.com','WFGV105'),

(1007,1001,1002,'Manglore',8242476234,8242476241,8242476252,
'banker25@karnatakabank.com','KBIN05267'),

(1000,1002,1000,'Puttur Market',8251249247,8251249247,8251249244,
'sbi.04270@sbi.co.in','SBIN004270');

--STEP 12 :CREATE TABLE CUSTOMER:
select * from bank.TBLCUSTOMER
CREATE TABLE BANK.TBLCUSTOMER              --CUSTOMER SHORT FORM IS (CST)
(
	CstId  BIGINT NOT NULL CONSTRAINT PK_Customer PRIMARY KEY IDENTITY(1000,1),
	
	CstAddId_Fk BIGINT NULL CONSTRAINT FK_Of_TblCustomer_from_tblAddress 
    REFERENCES BANK.TBLADDRESS(AddId),

	CstBranchId_Fk BIGINT NULL CONSTRAINT FK_Of_Tblcustomer_from_tblBranch 
    REFERENCES BANK.TBLBRANCH(BrId),

	CstFirstName VARCHAR(50)  NULL,
	CstLastName VARCHAR(50)  NULL,
	CstMidddleName VARCHAR(50)  NULL,
	CstDOB DATE NULL,
	CstSince DATE NULL,

	CstPhone1 NUMERIC(10,0) NULL CONSTRAINT Ck_CstPhone1 CHECK(LEN(CstPhone1)=10)
    CONSTRAINT Uq_CstPhone1 UNIQUE,

	CstPhone2 NUMERIC(10,0) NULL CONSTRAINT Ck_CstPhone2 CHECK(LEN(CstPhone2)=10),

	CstFax NUMERIC(10,0) NULL CONSTRAINT Ck_CstFax CHECK(LEN(CstFax)=10),

	CstGender VARCHAR(6) NULL CONSTRAINT Ck_CstGender 
	CHECK(CstGender='MALE' OR CstGender='FEMALE'),

	CstEmail VARCHAR(50) NULL CONSTRAINT Uq_CstEmail UNIQUE,
);

--STEP 13: INSERT DATA INTO TABLE CUSTOMER
 
INSERT INTO BANK.TBLCUSTOMER
VALUES
(1001,1002,'Nithin' ,'Kumar',NULL,'1985-11-09','1996',3234164705,NULL,NULL,
'Male','NithinKumar@gmail.com'),

(1002,1002,'Gaurao','Tarpe',NULL,'1986-12-25','2000',8242476235,NULL,NULL,
'Male','GauraoTarpe@gmail.com'),

(1001,1001,'Chaithra','Kunjathaya','Nithin','1990-01-19','2005',8251009246,NULL,NULL,
'FEMALE','ChaithraKunjathaya@yahoo.com'),

(1000,1002,'Adarsh','Hedge',NULL,'1990-01-19','2015',8251249246,NULL,NULL,
'MALE','AdarshHedge@hotmail.com'),

(1000,1002,'Nithin','Kumar',NULL,'1985-11-09','1996',9568745952,NULL,NULL,
'MALE','Nithin12Kumar@gmail.com'),

(1000,1001,'Nathan','Kamas',NULL,'1985-11-10','1996',9500045952,NULL,NULL,
'MALE','NathanKamas.com');


--STEP 14: CREATE TABLE ACCOUNTSTATUS:
 
CREATE TABLE ACCOUNT.TBLACCOUNTSTATUS         --ACCOUNT SHORT FORM (Acc)
(

	AccStatusCode CHAR(1) NOT NULL CONSTRAINT Pk_AccStatusCode PRIMARY KEY
	CONSTRAINT Ck_AccStatusCode CHECK (AccStatusCode='A' OR AccStatusCode='C'),
	AccStatusDesc CHAR(6) NULL CONSTRAINT Ck_AccStatusDesc
	CHECK (AccStatusDesc='Active' or AccStatusDesc='Closed')
);

--STEP 15 :INSERT DATA INTO TABLE ACCOUNTSTATUS:

INSERT INTO ACCOUNT.TBLACCOUNTSTATUS
VALUES
('A','Active'),
('C','Closed')

--STEP 16 :CREATE TABLE ACCOUNTTYPE:

CREATE TABLE ACCOUNT.TBLACCOUNTTYPE
(
	AccTypeCode VARCHAR(3) CONSTRAINT Pk_AccTypeCode PRIMARY KEY,
	AccTypeDesc VARCHAR(10) NULL
);

--STEP 17 :INSERT DATA INTO TABLE ACCOUNTTYPE:

INSERT INTO ACCOUNT.TBLACCOUNTTYPE
VALUES
('CHK','Checking'),
('SAV','Saving'),
('CUR','Current'),
('LN','Loan');

--STEP 18 : CREATE TABLE ACCOUNT:

CREATE TABLE ACCOUNT.TBLACCOUNT
(
	AccNumber BIGINT NOT NULL PRIMARY KEY IDENTITY(20000,1),
	
	AccStatusCode_Fk CHAR(1) NULL CONSTRAINT Fk_Of_Tblaccount_From_TblAccountStatus
	REFERENCES  ACCOUNT.TBLACCOUNTSTATUS (AccStatusCode),

	AccTypeCode_Fk VARCHAR(3) NULL CONSTRAINT Fk_Of_Tblaccount_From_TblAccountType
	REFERENCES ACCOUNT.TBLACCOUNTTYPE(AccTypeCode),

	AccCustomerId_Fk  BIGINT NULL CONSTRAINT Fk_Of_Tblaccount_From_TblCustomer
	REFERENCES BANK.TBLCUSTOMER(CstId),

	AccBalance FLOAT NULL
);



--STEP 19 :INSERT DATA INTO TABLE ACCOUNT

INSERT INTO ACCOUNT.TBLACCOUNT
VALUES
('A','CHK',1000,10000),
('A','SAV',1001,200000.9897),
('A','CUR',1002,30000.456),
('A','LN',1003,5000),
('C','CHK',1005,500);

--STEP 20 : CREATE TABLE TRANSACTIONTYPE

CREATE TABLE TRANSACTIONS.TBLTRANSACTIONTYPE     --SHORT FORM OF TRANSACTIONS IS (Tran)
(
	TranCodeId  BIGINT NOT NULL CONSTRAINT Pk_TranCodeId  PRIMARY KEY  IDENTITY (1000,1),
	TranTypeDesc VARCHAR(20)
);

--STEP 21 : INSERT DATA IN TABLE TRANSACTIONTYPE

INSERT INTO TRANSACTIONS.TBLTRANSACTIONTYPE 
VALUES
('Deposit'),
('WithDrawal');

--STEP 22 :CREATE TABLE TRANSACTION:

CREATE TABLE TRANSACTIONS.TBLTRANSACTION
(
	TranId BIGINT NOT NULL CONSTRAINT Pk_TranId PRIMARY KEY  IDENTITY(1000,1),
	
	TranAccountNumber_fk  BIGINT NULL CONSTRAINT FK_OF_TblTransaction_from_TblAccount
	REFERENCES ACCOUNT.TBLACCOUNT(AccNumber),

	TranCode_fk BIGINT NULL CONSTRAINT FK_OF_TblTransaction_from_TblTransactionType
	REFERENCES TRANSACTIONS.TBLTRANSACTIONTYPE  (TranCodeId),

	TranTransactionAmount FLOAT NULL,

	TranMerchat VARCHAR(30) NULL,

	TranDescription VARCHAR(40) NULL
);


--STEP 23:INSERT DATA INTO TABLE TRANSACTION:

INSERT INTO TRANSACTIONS.TBLTRANSACTION
VALUES
(20001,1000,20500.456,'Self','Self Deposit'),
(20000,1001,200000,'Discover','Withdrawal'),
(20002,1001,13.45,NULL,'Cheque #5001'),
(20001,1000,2500,'Self','Self Deposit'),
(20000,1000,25000,'Discover','Withdrawal'),
(20002,1000,1300.45,NULL,'Cheque#5001'),
(20001,1000,20500.456,'Self','Self Deposit'),
(20000,1001,200000,'Discover','Withdrawal'),
(20002,1001,13.45,NULL,'Cheque#5001'),
(20001,1000,20500.456,'Self','Self Deposit'),
(20001,1000,20500.456,'Self','Self Deposit'),
(20000,1000,25000,'Discover','Withdrawal'),
(20001,1000,20500.456,'Self','Self Deposit'),
(20002,1000,20500.456,'Self','Self Deposit'),
(20002,1001,25000,'Discover','Withdrawal');


--------END OF DESIGNING----








