--CREATE SYNONYM NAMES/ALTER NAME TO TABLE:

CREATE SYNONYM  sysBank   for BANK.TBLBANK;
CREATE SYNONYM  sysAddress  for BANK.TBLADDRESS;
CREATE SYNONYM  sysBranchType  for BANK.TBLBRANCHTYPE;
CREATE SYNONYM  sysBranch for BANK.TBLBRANCH;
CREATE SYNONYM  sysCustomer for BANK.TBLCUSTOMER;


CREATE SYNONYM  sysAccountStatus for ACCOUNT.TBLACCOUNTSTATUS;
CREATE SYNONYM  sysAccountType for ACCOUNT.TBLACCOUNTTYPE;
CREATE SYNONYM  sysAccount for ACCOUNT.TBLACCOUNT;

CREATE SYNONYM  sysTransactionType for TRANSACTIONS.TBLTRANSACTIONTYPE;
CREATE SYNONYM  sysTransaction for TRANSACTIONS.TBLTRANSACTION;


-- TEST SYNONYM USING SELECT:


SELECT * FROM sysBank; 
SELECT * FROM sysAddress;  
SELECT * FROM sysBranchType;
SELECT * FROM sysBranch; 
SELECT * FROM sysCustomer; 

SELECT * FROM sysAccountStatus;
SELECT * FROM sysAccountType; 
SELECT * FROM sysAccount; 

SELECT * FROM sysTransactionType;
SELECT * FROM sysTransaction;